import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { Modal } from "@/components/modal/Modal";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="h-screen">
        <Toaster />
        <Modal />
        {children}
      </body>
    </html>
  );
}
